export const titleOptions = [
  { value: '3d-artist', label: '3D Artist' },
  { value: 'engineer', label: 'Engineer' },
  { value: 'executive', label: 'Executive' },
  { value: 'senior', label: 'Senior' },
  { value: 'developer', label: 'Developer' },
  { value: 'finance', label: 'Finance' },
  { value: 'sys-admin', label: 'Sys Admin' },
  { value: 'javascript', label: 'JavaScript' },
  { value: 'backend', label: 'Backend' },
  { value: 'golang', label: 'Golang' },
  { value: 'cloud', label: 'Cloud' },
  { value: 'medical', label: 'Medical' },
  { value: 'front_end', label: 'Front End' },
  { value: 'full-stack', label: 'Full Stack' },
  { value: 'ops', label: 'Ops' },
  { value: 'design', label: 'Design' },
  { value: 'react', label: 'React' },
  { value: 'infosec', label: 'InfoSec' },
  { value: 'marketing', label: 'Marketing' },
  { value: 'mobile', label: 'Mobile' },
  { value: 'content-writing', label: 'Content Writing' },
  { value: 'saas', label: 'SaaS' },
  { value: 'recruiter', label: 'Recruiter' },
  { value: 'full-time', label: 'Full Time' },
  { value: 'api', label: 'API' },
  { value: 'sales', label: 'Sales' },
  { value: 'ruby', label: 'Ruby' },
  { value: 'education', label: 'Education' },
  { value: 'devops', label: 'DevOps' },
  { value: 'stats', label: 'Stats' },
  { value: 'python', label: 'Python' },
  { value: 'node', label: 'Node' },
  { value: 'english', label: 'English' },
  { value: 'non-tech', label: 'Non Tech' },
  { value: 'video', label: 'Video' },
  { value: 'travel', label: 'Travel' },
  { value: 'quality-assurance', label: 'Quality Assurance' },
  { value: 'ecommerce', label: 'Ecommerce' },
  { value: 'teaching', label: 'Teaching' },
  { value: 'linux', label: 'Linux' },
  { value: 'java', label: 'Java' },
  { value: 'crypto', label: 'Crypto' },
  { value: 'junior', label: 'Junior' },
  { value: 'git', label: 'Git' },
  { value: 'legal', label: 'Legal' },
  { value: 'android', label: 'Android' },
  { value: 'accounting', label: 'Accounting' },
  { value: 'admin', label: 'Admin' },
  { value: 'microsoft', label: 'Microsoft' },
  { value: 'excel', label: 'Excel' },
  { value: 'php', label: 'PHP' },
  { value: 'amazon', label: 'Amazon' },
  { value: 'serverless', label: 'Serverless' },
  { value: 'css', label: 'CSS' },
  { value: 'software', label: 'Software' },
  { value: 'analyst', label: 'Analyst' },
  { value: 'angular', label: 'Angular' },
  { value: 'ios', label: 'iOS' },
  { value: 'customer-support', label: 'Customer Support' },
  { value: 'html', label: 'HTML' },
  { value: 'salesforce', label: 'Salesforce' },
  { value: 'ads', label: 'Ads' },
  { value: 'product_designer', label: 'Product Designer' },
  { value: 'hr', label: 'HR' },
  { value: 'sql', label: 'SQL' },
  { value: 'c', label: 'C' },
  { value: 'web-developer', label: 'Web Developer' },
  { value: 'nosql', label: 'NoSQL' },
  { value: 'postgres', label: 'Postgres' },
  { value: 'c-plus-plus', label: 'C++' },
  { value: 'part-time', label: 'Part Time' },
  { value: 'jira', label: 'Jira' },
  { value: 'c-sharp', label: 'C#' },
  { value: 'seo', label: 'SEO' },
  { value: 'apache', label: 'Apache' },
  { value: 'datascience', label: 'Data Science' },
  { value: 'virtual-assistant', label: 'Virtual Assistant' },
  { value: 'react-native', label: 'React Native' },
  { value: 'mongo', label: 'Mongo' },
  { value: 'testing', label: 'Testing' },
  { value: 'architecture', label: 'Architecture' },
  { value: 'director', label: 'Director' },
  { value: 'music', label: 'Music' },
  { value: 'shopify', label: 'Shopify' },
  { value: 'wordpress', label: 'WordPress' },
  { value: 'laravel', label: 'Laravel' },
  { value: 'elasticsearch', label: 'Elasticsearch' },
  { value: 'blockchain', label: 'Blockchain' },
  { value: 'web3', label: 'Web3' },
  { value: 'drupal', label: 'Drupal' },
  { value: 'docker', label: 'Docker' },
  { value: 'graphql', label: 'GraphQL' },
  { value: 'payroll', label: 'Payroll' },
  { value: 'internship', label: 'Internship' },
  { value: 'machine-learning', label: 'Machine Learning' },
  { value: 'architect', label: 'Architect' },
  { value: 'scala', label: 'Scala' },
  { value: 'web', label: 'Web' },
  { value: 'objective-c', label: 'Objective C' },
  { value: 'social-media', label: 'Social Media' },
  { value: 'vue', label: 'Vue' },
  { value: 'data-entry', label: 'Data Entry' },
  { value: 'nursing', label: 'Nursing' },
  { value: 'human-resource', label: 'Human Resource' },
  { value: 'psychiatrist', label: 'Psychiatrist' },
];
